# -- Staging overrides --
env: staging
domain_name: "{{ ansible_host }}"
app_debug: true
app_log_level: "debug"
caddy_admin_email: "admin@staging.local"

# Use plain HTTP on the VM IP for local VM testing.
caddy_tls_mode: "disabled"
pod_publish_ports:
  - "80:80"
pod_caddy_config: "caddy/Caddyfile.staging"

# Skip backups in staging
backups_enabled: false

system_upgrade_packages: false
mail_mailer: "log"
mail_scheme: "null"
mail_host: "127.0.0.1"
mail_port: "2525"
mail_username: "null"
mail_password: "null"
